In [78]:
import numpy as np

In [79]:
# función que crea los arrays
def crear_arrays():
    # Creamos el primer array con algunos números
    array1 = np.array([88, 23, 39, 41])
    
    # Creamos el segundo array con dos listas diferentes
    array2 = np.array([[76.4, 76.5], [34.4, 45.6]])
    
    # Creamos un tercer array con cuatro números en vertical,No he podido meterlos todos en  un solo  []
    array3 = np.array([[1], [2], [3], [4]])
    
    # Devolvemos todos los arrays que hemos creado
    return array1, array2, array3


In [80]:
# información de los arrays
def info_arrays(arrays):
    # Recorrer cada array
    for a, array in enumerate(arrays, start=1):
        # Mostrar el array
        print(f"Array {a}:\n", array)  
        
        #  Número de elementos
        print("Número total d'elements:", array.size)  
        
        # La dimensión del array
        print("Dimensió de l'array:", array.shape)  
        
        # Tipo de elementos internos
        print("Tipus d’elements interns:", array.dtype)  
        
        # Mostrar el tamaño del array
        print("Tamany de l'array:", array.size)  
        print("\n")  # Añadir un salto de línea entre arrays


In [81]:
# Definir la función principal
def main():
    # Crear los arrays llamando a la función
    arrays = crear_arrays()  
    
    # Mostrar la información de los arrays
    info_arrays(arrays)  

# Verificar si estamos ejecutando este archivo directamente
if __name__ == "__main__":
    main()  


Array 1:
 [88 23 39 41]
Número total d'elements: 4
Dimensió de l'array: (4,)
Tipus d’elements interns: int64
Tamany de l'array: 4


Array 2:
 [[76.4 76.5]
 [34.4 45.6]]
Número total d'elements: 4
Dimensió de l'array: (2, 2)
Tipus d’elements interns: float64
Tamany de l'array: 4


Array 3:
 [[1]
 [2]
 [3]
 [4]]
Número total d'elements: 4
Dimensió de l'array: (4, 1)
Tipus d’elements interns: int64
Tamany de l'array: 4


