In [19]:
import numpy as np
#importamos biblioteca numpy

In [20]:
def matriz_diagonal():
    # Creamos una matriz de ceros de 7 filas y 7 columnas
    matriz = np.zeros((7, 7), dtype=int)
    
    # Llenamos la diagonal con números del 7 al 49 (sumando de 7 en 7)
    np.fill_diagonal(matriz, np.arange(7, 50, 7))
    
    return matriz


In [21]:
def info_matriz(matriz):
    #  matriz
    print("Matriz:")
    for fila in matriz:
        print(fila)  # Imprimir cada fila de la matriz

    # Dimension
    print("\nDimensión de la matriz:", matriz.shape)
    
    # tamaño(número de elementos)
    print("Tamaño de la matriz:", matriz.size)
    
    # elementos de la matriz
    print("Tipo de elementos internos:", matriz.dtype)


In [22]:
def main():
    # Crear la matriz
    matriz = matriz_diagonal()
    
    # Mostrar la información de la matriz
    info_matriz(matriz)

# Llamar a la función main
main()


Matriz:
[7 0 0 0 0 0 0]
[ 0 14  0  0  0  0  0]
[ 0  0 21  0  0  0  0]
[ 0  0  0 28  0  0  0]
[ 0  0  0  0 35  0  0]
[ 0  0  0  0  0 42  0]
[ 0  0  0  0  0  0 49]

Dimensión de la matriz: (7, 7)
Tamaño de la matriz: 49
Tipo de elementos internos: int64
