In [19]:
import numpy as np


In [20]:
def crear_matriu():
    # Crear una matriz de 3x4 con numeros aleatorios entre 0 y 80
    matriu = np.random.randint(0, 81, size=(3, 4))
    print("Matriz original de 3x4:\n", matriu)
    return matriu


In [21]:
def modificar_matriu(matriu):
    # Cambiar la matriz a 4x3
    matriu_modificada = matriu.T  #T = trasponer
    print("\nMatriz modificada a 4x3:\n", matriu_modificada)
    
    # giro de columnas 2 y 3 
    ultima_columna = matriu_modificada[:, -1]
    matriu_modificada = np.delete(matriu_modificada, -1, axis=1)  # Eliminar la ultima columna
    matriu_modificada = np.insert(matriu_modificada, -1, ultima_columna, axis=1)  # Insertar como ultima columna
    
    print("\nGiro de ultimas dos columnas:\n", matriu_modificada)
    
    return matriu_modificada


In [22]:
def modificar_ultima_columna(matriu):
    # Copiar numero 4ta columna
    valor_columna = matriu[:, -1][0]
    matriu[:, -1] = valor_columna  # Asignar el mismo valor a toda la ultima columna
    
    print("\nÚltima columna modificada:\n", matriu)
    
    return matriu


In [23]:
def main():
    # Crear la matriz original
    matriu = crear_matriu()
    
    # Modificar la matriz
    matriu_modificada = modificar_matriu(matriu)
    
    # Modificar la ultima columna
    matriu_final = modificar_ultima_columna(matriu_modificada)


In [24]:
if __name__ == "__main__":
    main()
#llamar funcion

Matriz original de 3x4:
 [[74 18 43 30]
 [ 0 51  5 33]
 [14 76 46 24]]

Matriz modificada a 4x3:
 [[74  0 14]
 [18 51 76]
 [43  5 46]
 [30 33 24]]

Giro de ultimas dos columnas:
 [[74 14  0]
 [18 76 51]
 [43 46  5]
 [30 24 33]]

Última columna modificada:
 [[74 14  0]
 [18 76  0]
 [43 46  0]
 [30 24  0]]
